
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=certuser
      - RABBITMQ_DEFAULT_PASS=securepassword123
      - RABBITMQ_DEFAULT_VHOST=tenant1
    volumes:
      # - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      # - ./rabbitmq/ssl:/etc/rabbitmq/ssl:ro  # Uncomment for SSL in production
    ports:
      - "127.0.0.1:9105:5672"  # AMQP
      - "127.0.0.1:9106:15672"  # Management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

# volumes:
#   rabbitmq_data:
#     name: rabbitmq_data